-- ============================================================
-- PRODUCCION - Miercoles 18/02/2026
-- Estructura: ProductionDay -> ProductionDough -> ProductionItem
-- Ejecutar con la app DETENIDA
-- ============================================================

-- ============================================================
-- 1. DIA DE PRODUCCION
-- ============================================================
INSERT INTO PRODUCTION_DAY (ID, PROD_DATE, NOTES)
  VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, '2026-02-18', 'Miercoles 18/Feb/2026');

-- ============================================================
-- 2. MASAS DEL DIA (PRODUCTION_DOUGH)
-- El numero en circulo de la hoja es MASS_PRODUCED
-- ============================================================

-- BG1 Baguette - circulo: 12 unidades de masa (12 x 310g = 3720g)
INSERT INTO PRODUCTION_DOUGH (ID, PRODUCTION_DAY_ID, DOUGH_ID, MASS_PRODUCED)
  VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,
    (SELECT ID FROM PRODUCTION_DAY WHERE PROD_DATE = '2026-02-18'),
    (SELECT ID FROM DOUGH WHERE CODE = 'BG1'),
    3720);

-- BO1 Bollito - circulo: 120 unidades (120 x 60g = 7200g)
INSERT INTO PRODUCTION_DOUGH (ID, PRODUCTION_DAY_ID, DOUGH_ID, MASS_PRODUCED)
  VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,
    (SELECT ID FROM PRODUCTION_DAY WHERE PROD_DATE = '2026-02-18'),
    (SELECT ID FROM DOUGH WHERE CODE = 'BO1'),
    7200);

-- CA1 Campesino - circulo: 9 unidades
-- 1x750 + 14x375 + 3x250 = 750 + 5250 + 750 = 6750g
INSERT INTO PRODUCTION_DOUGH (ID, PRODUCTION_DAY_ID, DOUGH_ID, MASS_PRODUCED)
  VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,
    (SELECT ID FROM PRODUCTION_DAY WHERE PROD_DATE = '2026-02-18'),
    (SELECT ID FROM DOUGH WHERE CODE = 'CA1'),
    6750);

-- DU1 Dulce - 15 unidades (15 x 60g = 900g)
INSERT INTO PRODUCTION_DOUGH (ID, PRODUCTION_DAY_ID, DOUGH_ID, MASS_PRODUCED)
  VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,
    (SELECT ID FROM PRODUCTION_DAY WHERE PROD_DATE = '2026-02-18'),
    (SELECT ID FROM DOUGH WHERE CODE = 'DU1'),
    900);

-- IN1 Integral - 3 unidades (3 x 435g = 1305g)
INSERT INTO PRODUCTION_DOUGH (ID, PRODUCTION_DAY_ID, DOUGH_ID, MASS_PRODUCED)
  VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,
    (SELECT ID FROM PRODUCTION_DAY WHERE PROD_DATE = '2026-02-18'),
    (SELECT ID FROM DOUGH WHERE CODE = 'IN1'),
    1305);

-- NE1 Negra - circulo: 8 unidades
-- 6x435 + 12x80 = 2610 + 960 = 3570g
INSERT INTO PRODUCTION_DOUGH (ID, PRODUCTION_DAY_ID, DOUGH_ID, MASS_PRODUCED)
  VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,
    (SELECT ID FROM PRODUCTION_DAY WHERE PROD_DATE = '2026-02-18'),
    (SELECT ID FROM DOUGH WHERE CODE = 'NE1'),
    3570);

-- OR1 Oregano - circulo: 8 unidades
-- 4x450 + 12x80 + 3x450 + 3x225 = 1800+960+1350+675 = 4785g
INSERT INTO PRODUCTION_DOUGH (ID, PRODUCTION_DAY_ID, DOUGH_ID, MASS_PRODUCED)
  VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,
    (SELECT ID FROM PRODUCTION_DAY WHERE PROD_DATE = '2026-02-18'),
    (SELECT ID FROM DOUGH WHERE CODE = 'OR1'),
    4785);

-- SE1 Semilla - circulo: 54 (5 Semilla + 4 Media Semilla)
-- 5x470 + 4x235 = 2350 + 940 = 3290g
INSERT INTO PRODUCTION_DOUGH (ID, PRODUCTION_DAY_ID, DOUGH_ID, MASS_PRODUCED)
  VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,
    (SELECT ID FROM PRODUCTION_DAY WHERE PROD_DATE = '2026-02-18'),
    (SELECT ID FROM DOUGH WHERE CODE = 'SE1'),
    3290);

-- FO1 Focaccia - 8 porciones (8 x 190g = 1520g)
INSERT INTO PRODUCTION_DOUGH (ID, PRODUCTION_DAY_ID, DOUGH_ID, MASS_PRODUCED)
  VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,
    (SELECT ID FROM PRODUCTION_DAY WHERE PROD_DATE = '2026-02-18'),
    (SELECT ID FROM DOUGH WHERE CODE = 'FO1'),
    1520);

-- ============================================================
-- 3. ITEMS DE PRODUCCION (PRODUCTION_ITEM)
-- qty_planned = solicitado, qty_produced = producido, qty_sold = sobrante
-- Nota: produccion anotada en rojo (el panadero olvido anotar en negro)
-- ============================================================

-- === BG1 Baguette ===
INSERT INTO PRODUCTION_ITEM (ID, PRODUCTION_DOUGH_ID, PRODUCT_ID, QTY_PLANNED, QTY_PRODUCED, QTY_SOLD, NOTES)
  VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,
    (SELECT PD.ID FROM PRODUCTION_DOUGH PD JOIN DOUGH D ON PD.DOUGH_ID=D.ID JOIN PRODUCTION_DAY DY ON PD.PRODUCTION_DAY_ID=DY.ID WHERE D.CODE='BG1' AND DY.PROD_DATE='2026-02-18'),
    (SELECT ID FROM PRODUCT WHERE CODE='BG-BAG'), 12, 12, 0, NULL);

INSERT INTO PRODUCTION_ITEM (ID, PRODUCTION_DOUGH_ID, PRODUCT_ID, QTY_PLANNED, QTY_PRODUCED, QTY_SOLD, NOTES)
  VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,
    (SELECT PD.ID FROM PRODUCTION_DOUGH PD JOIN DOUGH D ON PD.DOUGH_ID=D.ID JOIN PRODUCTION_DAY DY ON PD.PRODUCTION_DAY_ID=DY.ID WHERE D.CODE='BG1' AND DY.PROD_DATE='2026-02-18'),
    (SELECT ID FROM PRODUCT WHERE CODE='BG-MIN'), 3, 3, 0, NULL);

-- === BO1 Bollito ===
INSERT INTO PRODUCTION_ITEM (ID, PRODUCTION_DOUGH_ID, PRODUCT_ID, QTY_PLANNED, QTY_PRODUCED, QTY_SOLD, NOTES)
  VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,
    (SELECT PD.ID FROM PRODUCTION_DOUGH PD JOIN DOUGH D ON PD.DOUGH_ID=D.ID JOIN PRODUCTION_DAY DY ON PD.PRODUCTION_DAY_ID=DY.ID WHERE D.CODE='BO1' AND DY.PROD_DATE='2026-02-18'),
    (SELECT ID FROM PRODUCT WHERE CODE='BO-BOL'), 80, 82, 0, NULL);

INSERT INTO PRODUCTION_ITEM (ID, PRODUCTION_DOUGH_ID, PRODUCT_ID, QTY_PLANNED, QTY_PRODUCED, QTY_SOLD, NOTES)
  VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,
    (SELECT PD.ID FROM PRODUCTION_DOUGH PD JOIN DOUGH D ON PD.DOUGH_ID=D.ID JOIN PRODUCTION_DAY DY ON PD.PRODUCTION_DAY_ID=DY.ID WHERE D.CODE='BO1' AND DY.PROD_DATE='2026-02-18'),
    (SELECT ID FROM PRODUCT WHERE CODE='BO-MOL'), 3, 3, 2, 'Sobraron 2 moldes');

INSERT INTO PRODUCTION_ITEM (ID, PRODUCTION_DOUGH_ID, PRODUCT_ID, QTY_PLANNED, QTY_PRODUCED, QTY_SOLD, NOTES)
  VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,
    (SELECT PD.ID FROM PRODUCTION_DOUGH PD JOIN DOUGH D ON PD.DOUGH_ID=D.ID JOIN PRODUCTION_DAY DY ON PD.PRODUCTION_DAY_ID=DY.ID WHERE D.CODE='BO1' AND DY.PROD_DATE='2026-02-18'),
    (SELECT ID FROM PRODUCT WHERE CODE='BO-BRI'), 12, 12, 0, NULL);

-- === CA1 Campesino ===
INSERT INTO PRODUCTION_ITEM (ID, PRODUCTION_DOUGH_ID, PRODUCT_ID, QTY_PLANNED, QTY_PRODUCED, QTY_SOLD, NOTES)
  VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,
    (SELECT PD.ID FROM PRODUCTION_DOUGH PD JOIN DOUGH D ON PD.DOUGH_ID=D.ID JOIN PRODUCTION_DAY DY ON PD.PRODUCTION_DAY_ID=DY.ID WHERE D.CODE='CA1' AND DY.PROD_DATE='2026-02-18'),
    (SELECT ID FROM PRODUCT WHERE CODE='CA-CAM'), 1, 1, 0, NULL);

INSERT INTO PRODUCTION_ITEM (ID, PRODUCTION_DOUGH_ID, PRODUCT_ID, QTY_PLANNED, QTY_PRODUCED, QTY_SOLD, NOTES)
  VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,
    (SELECT PD.ID FROM PRODUCTION_DOUGH PD JOIN DOUGH D ON PD.DOUGH_ID=D.ID JOIN PRODUCTION_DAY DY ON PD.PRODUCTION_DAY_ID=DY.ID WHERE D.CODE='CA1' AND DY.PROD_DATE='2026-02-18'),
    (SELECT ID FROM PRODUCT WHERE CODE='CA-MED'), 14, 14, 0, NULL);

INSERT INTO PRODUCTION_ITEM (ID, PRODUCTION_DOUGH_ID, PRODUCT_ID, QTY_PLANNED, QTY_PRODUCED, QTY_SOLD, NOTES)
  VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,
    (SELECT PD.ID FROM PRODUCTION_DOUGH PD JOIN DOUGH D ON PD.DOUGH_ID=D.ID JOIN PRODUCTION_DAY DY ON PD.PRODUCTION_DAY_ID=DY.ID WHERE D.CODE='CA1' AND DY.PROD_DATE='2026-02-18'),
    (SELECT ID FROM PRODUCT WHERE CODE='CA-PAN'), 3, 3, 0, NULL);

-- === DU1 Dulce ===
INSERT INTO PRODUCTION_ITEM (ID, PRODUCTION_DOUGH_ID, PRODUCT_ID, QTY_PLANNED, QTY_PRODUCED, QTY_SOLD, NOTES)
  VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,
    (SELECT PD.ID FROM PRODUCTION_DOUGH PD JOIN DOUGH D ON PD.DOUGH_ID=D.ID JOIN PRODUCTION_DAY DY ON PD.PRODUCTION_DAY_ID=DY.ID WHERE D.CODE='DU1' AND DY.PROD_DATE='2026-02-18'),
    (SELECT ID FROM PRODUCT WHERE CODE='DU-DUL'), 15, 15, 0, NULL);

-- === IN1 Integral ===
INSERT INTO PRODUCTION_ITEM (ID, PRODUCTION_DOUGH_ID, PRODUCT_ID, QTY_PLANNED, QTY_PRODUCED, QTY_SOLD, NOTES)
  VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,
    (SELECT PD.ID FROM PRODUCTION_DOUGH PD JOIN DOUGH D ON PD.DOUGH_ID=D.ID JOIN PRODUCTION_DAY DY ON PD.PRODUCTION_DAY_ID=DY.ID WHERE D.CODE='IN1' AND DY.PROD_DATE='2026-02-18'),
    (SELECT ID FROM PRODUCT WHERE CODE='IN-INT'), 3, 3, 0, NULL);

-- === NE1 Negra ===
INSERT INTO PRODUCTION_ITEM (ID, PRODUCTION_DOUGH_ID, PRODUCT_ID, QTY_PLANNED, QTY_PRODUCED, QTY_SOLD, NOTES)
  VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,
    (SELECT PD.ID FROM PRODUCTION_DOUGH PD JOIN DOUGH D ON PD.DOUGH_ID=D.ID JOIN PRODUCTION_DAY DY ON PD.PRODUCTION_DAY_ID=DY.ID WHERE D.CODE='NE1' AND DY.PROD_DATE='2026-02-18'),
    (SELECT ID FROM PRODUCT WHERE CODE='NE-NEG'), 6, 6, 0, NULL);

INSERT INTO PRODUCTION_ITEM (ID, PRODUCTION_DOUGH_ID, PRODUCT_ID, QTY_PLANNED, QTY_PRODUCED, QTY_SOLD, NOTES)
  VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,
    (SELECT PD.ID FROM PRODUCTION_DOUGH PD JOIN DOUGH D ON PD.DOUGH_ID=D.ID JOIN PRODUCTION_DAY DY ON PD.PRODUCTION_DAY_ID=DY.ID WHERE D.CODE='NE1' AND DY.PROD_DATE='2026-02-18'),
    (SELECT ID FROM PRODUCT WHERE CODE='NE-MIN'), 12, 13, 0, NULL);

-- === OR1 Oregano ===
INSERT INTO PRODUCTION_ITEM (ID, PRODUCTION_DOUGH_ID, PRODUCT_ID, QTY_PLANNED, QTY_PRODUCED, QTY_SOLD, NOTES)
  VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,
    (SELECT PD.ID FROM PRODUCTION_DOUGH PD JOIN DOUGH D ON PD.DOUGH_ID=D.ID JOIN PRODUCTION_DAY DY ON PD.PRODUCTION_DAY_ID=DY.ID WHERE D.CODE='OR1' AND DY.PROD_DATE='2026-02-18'),
    (SELECT ID FROM PRODUCT WHERE CODE='OR-ORE'), 4, 4, 0, NULL);

INSERT INTO PRODUCTION_ITEM (ID, PRODUCTION_DOUGH_ID, PRODUCT_ID, QTY_PLANNED, QTY_PRODUCED, QTY_SOLD, NOTES)
  VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,
    (SELECT PD.ID FROM PRODUCTION_DOUGH PD JOIN DOUGH D ON PD.DOUGH_ID=D.ID JOIN PRODUCTION_DAY DY ON PD.PRODUCTION_DAY_ID=DY.ID WHERE D.CODE='OR1' AND DY.PROD_DATE='2026-02-18'),
    (SELECT ID FROM PRODUCT WHERE CODE='OR-MIN'), 12, 11, 0, NULL);

INSERT INTO PRODUCTION_ITEM (ID, PRODUCTION_DOUGH_ID, PRODUCT_ID, QTY_PLANNED, QTY_PRODUCED, QTY_SOLD, NOTES)
  VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,
    (SELECT PD.ID FROM PRODUCTION_DOUGH PD JOIN DOUGH D ON PD.DOUGH_ID=D.ID JOIN PRODUCTION_DAY DY ON PD.PRODUCTION_DAY_ID=DY.ID WHERE D.CODE='OR1' AND DY.PROD_DATE='2026-02-18'),
    (SELECT ID FROM PRODUCT WHERE CODE='OR-TOC'), 3, 3, 0, NULL);

INSERT INTO PRODUCTION_ITEM (ID, PRODUCTION_DOUGH_ID, PRODUCT_ID, QTY_PLANNED, QTY_PRODUCED, QTY_SOLD, NOTES)
  VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,
    (SELECT PD.ID FROM PRODUCTION_DOUGH PD JOIN DOUGH D ON PD.DOUGH_ID=D.ID JOIN PRODUCTION_DAY DY ON PD.PRODUCTION_DAY_ID=DY.ID WHERE D.CODE='OR1' AND DY.PROD_DATE='2026-02-18'),
    (SELECT ID FROM PRODUCT WHERE CODE='OR-MTO'), 3, 3, 0, NULL);

-- === SE1 Semilla ===
INSERT INTO PRODUCTION_ITEM (ID, PRODUCTION_DOUGH_ID, PRODUCT_ID, QTY_PLANNED, QTY_PRODUCED, QTY_SOLD, NOTES)
  VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,
    (SELECT PD.ID FROM PRODUCTION_DOUGH PD JOIN DOUGH D ON PD.DOUGH_ID=D.ID JOIN PRODUCTION_DAY DY ON PD.PRODUCTION_DAY_ID=DY.ID WHERE D.CODE='SE1' AND DY.PROD_DATE='2026-02-18'),
    (SELECT ID FROM PRODUCT WHERE CODE='SE-SEM'), 5, 5, 0, NULL);

INSERT INTO PRODUCTION_ITEM (ID, PRODUCTION_DOUGH_ID, PRODUCT_ID, QTY_PLANNED, QTY_PRODUCED, QTY_SOLD, NOTES)
  VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,
    (SELECT PD.ID FROM PRODUCTION_DOUGH PD JOIN DOUGH D ON PD.DOUGH_ID=D.ID JOIN PRODUCTION_DAY DY ON PD.PRODUCTION_DAY_ID=DY.ID WHERE D.CODE='SE1' AND DY.PROD_DATE='2026-02-18'),
    (SELECT ID FROM PRODUCT WHERE CODE='SE-MED'), 4, 4, 0, NULL);

-- === FO1 Focaccia ===
INSERT INTO PRODUCTION_ITEM (ID, PRODUCTION_DOUGH_ID, PRODUCT_ID, QTY_PLANNED, QTY_PRODUCED, QTY_SOLD, NOTES)
  VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE,
    (SELECT PD.ID FROM PRODUCTION_DOUGH PD JOIN DOUGH D ON PD.DOUGH_ID=D.ID JOIN PRODUCTION_DAY DY ON PD.PRODUCTION_DAY_ID=DY.ID WHERE D.CODE='FO1' AND DY.PROD_DATE='2026-02-18'),
    (SELECT ID FROM PRODUCT WHERE CODE='FO-POR'), 8, 8, 2, 'Sobraron 2 porciones');

-- ============================================================
-- VERIFICACION - ejecutar despues del INSERT para confirmar
-- ============================================================
-- SELECT DY.PROD_DATE, D.NAME AS MASA, P.NAME AS PRODUCTO,
--        PI.QTY_PLANNED, PI.QTY_PRODUCED, PI.QTY_SOLD
-- FROM PRODUCTION_DAY DY
-- JOIN PRODUCTION_DOUGH PD ON PD.PRODUCTION_DAY_ID = DY.ID
-- JOIN DOUGH D ON PD.DOUGH_ID = D.ID
-- JOIN PRODUCTION_ITEM PI ON PI.PRODUCTION_DOUGH_ID = PD.ID
-- JOIN PRODUCT P ON PI.PRODUCT_ID = P.ID
-- WHERE DY.PROD_DATE = '2026-02-18'
-- ORDER BY D.NAME, P.NAME;
-- ============================================================
